# -*- coding: utf-8 -*-
"""Builds all inner pages of radicalpolymer.com from index.html's header/footer + content.py.
Run from repo root:  python3 _build/build.py
"""
import os, re, html, sys
sys.path.insert(0, os.path.dirname(__file__))
from content import *

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
IDX = open(os.path.join(ROOT, 'index.html'), encoding='utf-8').read()
esc = html.escape

def U(key, w=1200, q=75):
    pid = IMG.get(key, key)
    return f'https://images.unsplash.com/photo-{pid}?auto=format&fit=crop&w={w}&q={q}'

def img(key, w=1200, alt='', eager=False):
    lz = '' if eager else ' loading="lazy"'
    return f'<img src="{U(key, w)}" alt="{esc(alt)}"{lz}>'

def between(a, b):
    i = IDX.index(a); j = IDX.index(b, i)
    return IDX[i:j]

# ---------- shared assets ----------
def build_assets():
    css = re.search(r'<style>(.*?)</style>', IDX, re.S).group(1)
    inner = open(os.path.join(ROOT, '_build', 'inner.css'), encoding='utf-8').read()
    os.makedirs(os.path.join(ROOT, 'assets', 'css'), exist_ok=True)
    open(os.path.join(ROOT, 'assets', 'css', 'style.css'), 'w', encoding='utf-8').write('/* Generated by _build/build.py from index.html + _build/inner.css */\n' + css.strip() + '\n' + inner)

HEAD_LINKS = re.search(r'(<link rel="preconnect".*?font-awesome[^>]*>)', IDX, re.S).group(1)
TOP = between('<div class="prog"></div>', '<!-- 3. HERO -->')
FOOT = between('<!-- 19. FOOTER -->', '<script>')
ENQ = between('<!-- 18. ENQUIRY + MAP -->', '<!-- 19. FOOTER -->')
TOP = TOP.replace('<li class="act"><a href="index.html">Home</a></li>', '<li><a href="index.html">Home</a></li>')

NAV_KEYS = {'about': 'about-us.html', 'products': 'products.html', 'industries': 'industries.html', 'manufacturing': 'manufacturing.html',
            'why': 'why-choose-us.html', 'testimonials': 'testimonials.html', 'blog': 'blog.html', 'contact': 'contact-us.html'}

def header(active):
    t = TOP
    if active in NAV_KEYS:
        href = NAV_KEYS[active]
        t = t.replace(f'<li><a href="{href}">', f'<li class="act"><a href="{href}">', 1)
        t = t.replace(f'<li class="has-dd"><a href="{href}">', f'<li class="has-dd act"><a href="{href}">', 1)
    return t

def page(fname, title, desc, active, body, product=None):
    enq_present = 'id="enquiry"' in body
    out = f'''<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>{esc(title)}</title>
<meta name="description" content="{esc(desc)}">
<meta property="og:title" content="{esc(title)}"><meta property="og:description" content="{esc(desc)}"><meta property="og:type" content="website">
<link rel="icon" href="logo.png">
{HEAD_LINKS}
<link rel="stylesheet" href="assets/css/style.css">
</head>
<body>
{header(active)}
<main>
{body}
</main>
{FOOT}<script src="assets/js/main.js"></script>
</body>
</html>
'''
    if product:
        out = out.replace(f'<option>{product}</option>', f'<option selected>{product}</option>')
    open(os.path.join(ROOT, fname), 'w', encoding='utf-8').write(out)
    PAGES.append(fname)

PAGES = []

# ---------- components ----------
def phero(crumbs, eyebrow, title, sub, im, chips=(), card=True, acts=True, extra=''):
    cr = '<a href="index.html"><i class="fa-solid fa-house" style="font-size:12px;color:var(--gold2)"></i> Home</a>'
    for c in crumbs:
        cr += f' <i class="fa-solid fa-chevron-right"></i> ' + (f'<a href="{c[1]}">{c[0]}</a>' if len(c) > 1 else f'<span>{c[0]}</span>')
    ch = ''.join(f'<span><i class="fa-solid fa-circle-check"></i>{c}</span>' for c in chips)
    a = ('<div class="acts"><a href="#" class="btn btn-g" data-open-enquiry>Get a Free Quote <i class="fa-solid fa-arrow-right"></i></a>'
         '<a href="tel:+919711114333" class="btn btn-l"><i class="fa-solid fa-phone"></i> +91 9711114333</a></div>') if acts else ''
    cd = '''<div class="ph-card"><div class="row"><i class="fa-solid fa-phone"></i><div><small>Call Us</small><b><a href="tel:+919711114333">+91 9711114333</a></b></div></div>
<div class="row"><i class="fa-regular fa-envelope"></i><div><small>Email Us</small><b><a href="mailto:sales@radicalpolymer.com">sales@radicalpolymer.com</a></b></div></div>
<div class="row"><i class="fa-regular fa-clock"></i><div><small>Working Hours</small><b>Mon – Sat: 9:30 AM – 7:00 PM</b></div></div>
<a href="#" class="btn btn-g" data-open-enquiry>Request a Quote <i class="fa-solid fa-paper-plane"></i></a></div>''' if card else ''
    return f'''<section class="phero"><div class="bg">{img(im, 1900, '', True)}</div><div class="wrap">
 <div><nav class="crumb" aria-label="Breadcrumb">{cr}</nav><span class="eyebrow">{eyebrow}</span><h1>{title}</h1><p class="sub">{sub}</p>{extra}{a}{f'<div class="chips">{ch}</div>' if ch else ''}</div>
 {cd}
</div></section>'''

def head(eyebrow, title, lead='', center=False, side=''):
    l = f'<p class="lead">{lead}</p>' if lead else ''
    if center:
        return f'<div class="center rv" style="margin-bottom:50px"><span class="eyebrow">{eyebrow}</span><h2 class="h2">{title}</h2>{l}</div>'
    return f'<div class="sec-head rv"><div><span class="eyebrow">{eyebrow}</span><h2 class="h2" style="margin:0">{title}</h2></div>{side or l}</div>'

def strip():
    return '''<section class="strip"><div class="wrap">
 <div class="si rv"><i class="fa-solid fa-industry"></i><div><b>Direct Manufacturer</b><span>No middlemen pricing</span></div></div>
 <div class="si rv d1"><i class="fa-solid fa-ruler-combined"></i><div><b>Custom Sizes</b><span>From drawing or sample</span></div></div>
 <div class="si rv d2"><i class="fa-solid fa-shield-halved"></i><div><b>Quality Checked</b><span>Every lot inspected</span></div></div>
 <div class="si rv d3"><i class="fa-solid fa-truck-fast"></i><div><b>Pan-India Delivery</b><span>On promised time-frame</span></div></div>
 <div class="si rv d4"><i class="fa-solid fa-headset"></i><div><b>Quick Support</b><span>Response within 24 hrs</span></div></div>
</div></section>'''

def stats(bg='orange'):
    return f'''<section class="stats"><div class="bgi">{img(bg, 1800)}</div><div class="wrap">
 <div class="sb rv"><i class="fa-solid fa-box-open"></i><div class="n" data-count="20">0</div><span>Products</span></div>
 <div class="sb rv d1"><i class="fa-solid fa-user-gear"></i><div class="n" data-count="80">0</div><span>Expert Members</span></div>
 <div class="sb rv d2"><i class="fa-solid fa-clipboard-check"></i><div class="n" data-count="200">0</div><span>Projects Completed</span></div>
 <div class="sb rv d3"><i class="fa-solid fa-gears"></i><div class="n" data-count="20">0</div><span>Modern Equipment</span></div>
 <div class="sb rv d4"><i class="fa-solid fa-face-smile"></i><div class="n" data-count="350">0</div><span>Happy Clients</span></div>
</div></section>'''

def cta(title, sub, im='sparks', pad='110px'):
    return f'''<section style="padding:{pad} 0"><div class="wrap"><div class="cta-b rv">
 <div class="img">{img(im, 1800)}</div>
 <div><h2>{title}</h2><p>{sub}</p></div>
 <div class="acts"><a href="#" class="btn btn-g" data-open-enquiry>Get Free Quote <i class="fa-solid fa-arrow-right"></i></a><a href="tel:+919711114333" class="btn btn-l"><i class="fa-solid fa-phone"></i> +91 9711114333</a></div>
</div></div></section>'''

_uid = [0]
def uid(p):
    _uid[0] += 1; return f'{p}{_uid[0]}'

def testimonials(soft=True):
    i = uid('t')
    cards = ''.join(f'<div class="tc"><div class="av">{a}</div><div><div class="st">★★★★★</div><p>“{esc(q)}”</p><b>{n}</b><span>{r}</span></div><i class="fa-solid fa-quote-right qm"></i></div>' for a, n, r, q in TESTIMONIALS)
    return f'''<section class="sec testi{" u-soft" if soft else ""}"><div class="wrap">
 <div class="sec-head rv"><div><span class="eyebrow"><i class="fa-solid fa-comments"></i> Testimonials</span><h2 class="h2" style="margin:0">What Clients <em>Say About Us</em></h2></div>
  <div style="display:flex;gap:16px;align-items:center;flex-wrap:wrap"><div class="t-sum"><b>5.0</b><div><span class="st">★★★★★</span><small>from our happy clients</small></div></div><div class="sl-ctrl" id="{i}"><button class="ar prev" aria-label="Previous"><i class="fa-solid fa-arrow-left"></i></button><button class="ar next" aria-label="Next"><i class="fa-solid fa-arrow-right"></i></button></div></div></div>
 <div class="slider rv" data-ctrl="#{i}"><div class="sl-track">{cards}</div><div class="sl-dots"></div></div>
</div></section>'''

def blog_card(b):
    return f'''<a href="{b["slug"]}.html" class="bc" data-c="{b["cat"].lower().replace(" ", "-")}"><div class="img">{img(b["img"], 800)}<span class="cat">{b["cat"]}</span></div><div class="bb"><div class="meta"><span><i class="fa-regular fa-calendar"></i>{b["date"]}</span><span><i class="fa-regular fa-clock"></i>{b["mins"]} min read</span></div><h3>{b["title"]}</h3><p>{b["excerpt"]}</p><span class="rm">Read Article <i class="fa-solid fa-arrow-right"></i></span></div></a>'''

def blog_slider(exclude=None, title='From Our <em>Knowledge Hub</em>'):
    i = uid('b')
    cards = ''.join(blog_card(b) for b in BLOG if b['slug'] != exclude)
    return f'''<section class="sec blog"><div class="wrap">
 <div class="sec-head rv"><div><span class="eyebrow"><i class="fa-solid fa-newspaper"></i> Blog &amp; Insights</span><h2 class="h2" style="margin:0">{title}</h2></div><div class="sl-ctrl" id="{i}"><a href="blog.html" class="btn btn-l">View All</a><button class="ar prev" aria-label="Previous"><i class="fa-solid fa-arrow-left"></i></button><button class="ar next" aria-label="Next"><i class="fa-solid fa-arrow-right"></i></button></div></div>
 <div class="slider rv" data-ctrl="#{i}"><div class="sl-track">{cards}</div><div class="sl-dots"></div></div>
</div></section>'''

def faq(items, im='clipboard', title='Frequently Asked <em>Questions</em>', soft=False):
    qs = ''.join(f'<div class="fq{" open" if k == 0 else ""}"><button>{esc(q)}<span><i class="fa-solid fa-plus"></i></span></button><div class="a"><div><p>{esc(a)}</p></div></div></div>' for k, (q, a) in enumerate(items))
    return f'''<section class="sec faq{" u-soft" if soft else ""}"><div class="wrap">
 <div class="rv"><span class="eyebrow"><i class="fa-solid fa-circle-question"></i> FAQ</span><h2 class="h2">{title}</h2><p class="lead">Quick answers to the questions we hear most from our clients.</p>
  <div class="faq-img img">{img(im, 900)}</div>
  <div class="faq-help"><i class="fa-solid fa-headset"></i><div><span style="color:var(--mut);font-size:14px">Still have questions?</span><b><a href="tel:+919711114333">Call +91 9711114333</a></b></div></div></div>
 <div class="rv d1">{qs}</div>
</div></section>'''

def enquiry():
    return ENQ

def mat_table(side=True):
    rows = ''.join(f'<tr><td>{n}</td><td>{b}</td><td>{t}</td><td><div class="bar"><i style="--w:{o}%"></i></div></td></tr>' for n, s, b, t, o in MATERIALS)
    tbl = f'<div class="tbl-wrap rv"><table class="mat-t"><thead><tr><th>Material</th><th>Best For</th><th>Temp. Range (approx.)</th><th>Oil Resistance</th></tr></thead><tbody>{rows}</tbody></table></div>'
    if not side:
        return tbl
    return f'''<div class="mat-wrap">{tbl}<div class="mat-side img rv d1">{img("lab", 800)}<div><h3>Not sure which material?</h3><p>Share your temperature, media and pressure — we'll recommend the right compound.</p><a href="#" class="btn btn-g" data-open-enquiry>Ask Our Expert <i class="fa-solid fa-comments"></i></a></div></div></div>'''

def materials_sec(soft=True):
    return f'''<section class="sec mats{" u-soft" if soft else ""}"><div class="wrap">
 {head('<i class="fa-solid fa-flask"></i> Material Guide', 'Choose The <em>Right Rubber</em>', "Not sure which compound fits your application? Here's a quick guide — our team will help you finalise.")}
 {mat_table()}
</div></section>'''

PROCESS = [('fa-solid fa-magnifying-glass', 'Explore', 'We understand your application, dimensions, material and volume requirements.', 'blueprint'),
           ('fa-solid fa-pen-ruler', 'Design', 'Compound selection, drawing approval and mould development.', 'cad'),
           ('fa-solid fa-gears', 'Production', 'Precision moulding on modern machines with in-process quality checks.', 'operator'),
           ('fa-solid fa-truck-ramp-box', 'Finished', 'Final inspection, packing and on-time dispatch to your doorstep.', 'boxes')]

def process_tl(soft=False, title='Our Work <em>Process</em>'):
    items = ''
    for k, (ic, t, d, im) in enumerate(PROCESS):
        box = f'<div class="box rv"><div class="img">{img(im, 400)}</div><div class="tx"><small>STEP 0{k+1}</small><h3><i class="{ic}" style="color:var(--gold)"></i>{t}</h3><p>{d}</p></div></div>'
        items += (f'<div class="ts">{box}<div class="dot">0{k+1}</div></div>' if k % 2 == 0 else f'<div class="ts right"><div class="dot">0{k+1}</div>{box}</div>')
    return f'''<section class="sec{" u-soft" if soft else ""}"><div class="wrap">
 <div class="center rv"><span class="eyebrow"><i class="fa-solid fa-diagram-project"></i> How It Works</span><h2 class="h2">{title}</h2><p class="lead">From your first enquiry to final dispatch — a simple, transparent four-step process.</p></div>
 <div class="tl"><div class="fill"></div>{items}</div>
</div></section>'''

def steps4(items=None, dark=False):
    items = items or [(ic, t, d) for ic, t, d, _ in PROCESS]
    return '<div class="steps4">' + ''.join(f'<div class="st4 rv d{k}"><span class="n">0{k+1}</span><i class="{ic}"></i><h3>{t}</h3><p>{d}</p></div>' for k, (ic, t, d) in enumerate(items)) + '</div>'

def industries_grid(dark=True, title='Industries <em>We Serve</em>', exclude=None):
    cards = ''
    for k, ind in enumerate(x for x in INDUSTRIES if x['slug'] != exclude):
        cards += f'<a href="{ind["slug"]}.html" class="ic-card rv d{k}"><div class="img">{img(ind["img"], 700, ind["name"])}</div><span class="ii"><i class="{ind["icon"]}"></i></span><h3>{ind["name"]}</h3><p>{ind["tagline"]}</p><span class="go">Explore <i class="fa-solid fa-arrow-right"></i></span></a>'
    n = 5 if not exclude else 4
    return f'''<section class="sec{" ind" if dark else ""}"><div class="wrap">
 {head('<i class="fa-solid fa-city"></i> Industries', title, 'Our rubber components keep critical equipment sealed, cushioned and running across five core sectors.')}
 <div class="ind-g cols-{n}">{cards}</div>
</div></section>'''

def product_card(p, k=0):
    tag = f'<span class="tagp">{p["tag"]}</span>' if p.get('tag') else ''
    return f'<a href="{p["slug"]}.html" class="pc rv d{k % 5}" data-c="{p["cat"]}"><div class="img">{img(p["img"], 700, p["name"])}{tag}<span class="ico"><i class="{p["icon"]}"></i></span></div><div class="pb"><h3>{p["name"]}</h3><p>{p["card"]}</p><span class="lk">Read More <i class="fa-solid fa-arrow-right"></i></span></div></a>'

def products_grid(slugs=None, title='Explore Our <em>Product Range</em>', soft=True, eyebrow='Our Products'):
    ps = [P[s] for s in slugs] if slugs else PRODUCTS
    cols = min(len(ps), 5) if len(ps) != 6 else 3
    cards = ''.join(product_card(p, k) for k, p in enumerate(ps))
    return f'''<section class="sec prods{" u-soft" if soft else ""}"><div class="wrap">
 {head(f'<i class="fa-solid fa-boxes-stacked"></i> {eyebrow}', title, side='<a href="products.html" class="btn btn-d">View All Products <i class="fa-solid fa-arrow-right"></i></a>')}
 <div class="pg cols-{cols}">{cards}</div>
</div></section>'''

def gallery(keys, labels, title='Inside Our <em>Facility</em>'):
    items = ''.join(f'<div class="img" data-lb>{img(k, 1200 if n == 0 else 800, l[0])}<span class="zoom"><i class="fa-solid fa-expand"></i></span><div class="lbl"><b>{l[0]}</b><span>{l[1]}</span></div></div>' for n, (k, l) in enumerate(zip(keys, labels)))
    return f'''<section class="sec"><div class="wrap">
 {head('<i class="fa-solid fa-images"></i> Gallery', title, side='<a href="manufacturing-facility.html" class="btn btn-l">Explore Facility <i class="fa-solid fa-arrow-right"></i></a>')}
 <div class="gal rv">{items}</div>
</div></section>'''

def fcards(items, cols=3, numbered=False):
    return f'<div class="g{cols}">' + ''.join(f'<div class="fc rv d{k % 4}">{f"<span class=num>0{k+1}</span>" if numbered else ""}<div class="ic"><i class="{ic}"></i></div><h3>{t}</h3><p>{d}</p></div>' for k, (ic, t, d) in enumerate(items)) + '</div>'

def split(pic_key, inner, badge=None, mini=None, rev=False, sm=False, soft=False, pad=''):
    b = f'<div class="pic-badge{" dark" if badge and badge[2] else ""}"><b>{badge[0]}</b><span>{badge[1]}</span></div>' if badge else ''
    m = f'<div class="pic-mini img">{img(mini, 500)}</div>' if mini else ''
    return f'''<section class="sec{" u-soft" if soft else ""}"{pad}><div class="wrap split{" rev" if rev else ""}">
 <div class="pic-wrap rv"><div class="pic img{" sm" if sm else ""}">{img(pic_key, 1100)}</div>{m}{b}</div>
 <div class="rv d1">{inner}</div>
</div></section>'''

def tk(items, c2=True):
    return f'<ul class="tk{" c2" if c2 else ""}">' + ''.join(f'<li><i class="fa-solid fa-circle-check"></i>{x}</li>' for x in items) + '</ul>'

WHY8 = [('fa-solid fa-industry', 'Genuine Manufacturer', 'Factory-direct supply with full control over quality and cost.'),
        ('fa-solid fa-ruler-combined', 'Any Size Developed', 'Custom moulds developed from your drawing or sample.'),
        ('fa-solid fa-flask-vial', 'Right Compound', 'NBR, EPDM, Silicone, Viton, Neoprene — matched to your application.'),
        ('fa-solid fa-microscope', 'Inspected Quality', 'Dimensions, hardness and finish checked on every lot.'),
        ('fa-solid fa-indian-rupee-sign', 'Reasonable Rates', 'Competitive pricing for small runs and bulk orders.'),
        ('fa-solid fa-truck-fast', 'On-Time Delivery', 'Dispatched across India within the promised time-frame.'),
        ('fa-solid fa-boxes-stacked', 'Flexible Quantities', 'From sample batches to regular bulk supply.'),
        ('fa-solid fa-headset', 'Responsive Support', 'Quick quotations and direct access to our team.')]

# ================= PAGES =================
def about():
    body = phero([('About Us',)], '<i class="fa-solid fa-building"></i> About Us', 'Rubber Products Built on <em>Quality &amp; Trust</em>',
                 'Since 2013, Radical Polymers has manufactured rubber O-rings, seals, gaskets and custom parts in Ghaziabad — at reasonable rates and on promised timelines.',
                 'engineers', ['Established 2013', '350+ Happy Clients', 'Pan-India Delivery'])
    body += strip()
    body += split('techs', f'''<span class="eyebrow"><i class="fa-solid fa-building"></i> Who We Are</span>
<h2 class="h2">Welcome To <em>Radical Polymers</em></h2>
<p>Established as a Proprietor firm in the year 2013, “Radical Polymers” is a leading Manufacturer of a wide range of Rubber Gaskets, Rubber O-Rings, Rubber Seals, etc. Situated in Ghaziabad (Uttar Pradesh, India), we have constructed a wide and well-functional infrastructural unit that plays an important role in the growth of our company.</p>
<p>We offer these products at reasonable rates and deliver them within the promised time-frame. Under the headship of <b style="color:var(--ink)">Mr. Sahil Sharma</b> (Proprietor), we have gained a huge clientele across the nation.</p>
<div data-tabs><div class="mv-tabs"><button class="on" data-t="m"><i class="fa-solid fa-bullseye"></i>Our Mission</button><button data-t="v"><i class="fa-regular fa-eye"></i>Our Vision</button><button data-t="val"><i class="fa-regular fa-gem"></i>Our Values</button></div>
<p class="mv-p on" data-p="m">To supply reliable rubber components at reasonable rates and deliver them within the promised time-frame — every single order.</p>
<p class="mv-p" data-p="v">To be the first-choice rubber parts partner for Indian manufacturers, known for quality, flexibility and trust.</p>
<p class="mv-p" data-p="val">Honest pricing, consistent quality, quick response and long-term relationships with every client.</p></div>
<div class="owner"><div class="av">S</div><div><b>Mr. Sahil Sharma</b><span>Proprietor, Radical Polymers</span></div><a href="#" class="btn btn-g" style="margin-left:auto" data-open-enquiry>Work With Us <i class="fa-solid fa-arrow-right"></i></a></div>''',
                  badge=('2013', 'Established in Ghaziabad', False), mini='oring2')
    body += stats('floor')
    jr = [('fa-solid fa-flag', 'The Beginning', '2013', 'Founded as a Proprietor firm in Ghaziabad, Uttar Pradesh.'),
          ('fa-solid fa-boxes-stacked', 'Wider Range', 'Growth', 'Expanded from O-rings and gaskets to seals, bushes, diaphragms and more.'),
          ('fa-solid fa-pen-ruler', 'Custom Development', 'Capability', 'Developing parts from drawings and samples for OEMs and spares.'),
          ('fa-solid fa-handshake', '350+ Clients', 'Today', 'A trusted supplier to clients across automotive, industrial and engineering sectors.')]
    body += f'''<section class="sec"><div class="wrap">{head('<i class="fa-solid fa-route"></i> Our Journey', 'How We <em>Grew</em>', '', True)}
 <div class="jr">''' + ''.join(f'<div class="it rv d{k}"><div class="dot"><i class="{ic}"></i></div><small>{y}</small><h3>{t}</h3><p>{d}</p></div>' for k, (ic, t, y, d) in enumerate(jr)) + '</div></div></section>'
    body += f'''<section class="sec u-soft"><div class="wrap">{head('<i class="fa-solid fa-gem"></i> Our Values', 'What We <em>Stand For</em>', 'The principles that guide every order we take on.')}
 {fcards([('fa-solid fa-award', 'Quality First', 'Every part is checked before it leaves our facility.'), ('fa-solid fa-scale-balanced', 'Honest Pricing', 'Fair, transparent, factory-direct rates.'),
          ('fa-solid fa-clock', 'On-Time Delivery', 'We commit to timelines and keep them.'), ('fa-solid fa-lightbulb', 'Problem Solving', 'We help select the right compound and design.'),
          ('fa-solid fa-handshake', 'Long-Term Relations', 'Most of our business comes from repeat clients.'), ('fa-solid fa-users-gear', 'Skilled People', 'An experienced team of 80+ members.')], 3, True)}
</div></section>'''
    body += f'''<section class="sec"><div class="wrap"><div class="leader rv">
 <div class="img">{img('handshake', 1000, 'Client partnership')}</div>
 <div class="tx"><span class="q">“</span><blockquote>Our commitment is simple: rubber parts that fit right, perform reliably and arrive when promised — at a price that makes sense for our clients.</blockquote><b>Radical Polymers</b><span>Led by Mr. Sahil Sharma, Proprietor</span></div>
</div></div></section>'''
    body += split('floor', f'''<span class="eyebrow"><i class="fa-solid fa-warehouse"></i> Infrastructure</span><h2 class="h2">A Well-Equipped <em>Manufacturing Unit</em></h2>
<p>Our Ghaziabad unit houses modern moulding presses, finishing and inspection equipment, operated by a skilled team. Every stage — from compound selection to final packing — happens under one roof.</p>
{tk(['Compression & injection moulding', '20+ modern machines', 'In-house mould development', 'Dimensional & hardness checks', 'Organised packing & dispatch', '80+ skilled team members'])}
<a href="manufacturing-facility.html" class="btn btn-d">Explore Our Facility <i class="fa-solid fa-arrow-right"></i></a>''', badge=('20+', 'Modern machines', True), rev=True, soft=True)
    body += industries_grid()
    body += testimonials()
    body += cta('Looking for a <em>Reliable Rubber Partner</em>?', 'Talk to our team about your requirement — standard or custom.')
    body += faq(GENERAL_FAQS, 'designteam')
    body += enquiry()
    page('about-us.html', 'About Us | Radical Polymers – Rubber Products Manufacturer, Ghaziabad',
         'Radical Polymers, established 2013 in Ghaziabad, manufactures rubber O-rings, seals, gaskets and custom rubber parts at reasonable rates with on-time delivery.', 'about', body)

def products():
    body = phero([('Products',)], '<i class="fa-solid fa-boxes-stacked"></i> Our Products', 'Rubber Products for <em>Every Application</em>',
                 'O-rings, seals, gaskets, washers, sheets, bushes, profiles, diaphragms and custom moulded parts — in NBR, EPDM, Silicone, Viton, Neoprene and Natural Rubber.',
                 'oring2', ['10 Product Ranges', 'Custom Sizes', 'Multiple Compounds'])
    body += strip()
    cats = [('all', 'All Products'), ('seal', 'Sealing'), ('mount', 'Mounting & Vibration'), ('sheet', 'Sheets & Profiles'), ('custom', 'Custom & Molded')]
    flt = '<div class="filters" data-filter="#plist">' + ''.join(f'<button{" class=on" if k == 0 else ""} data-f="{c}">{n}</button>' for k, (c, n) in enumerate(cats)) + '</div>'
    cards = ''
    for k, p in enumerate(PRODUCTS):
        li = ''.join(f'<li><i class="fa-solid fa-check"></i>{f[1]}</li>' for f in p['features'][:3])
        cards += f'''<div class="plc rv" data-c="{p['cat']}"><div class="img">{img(p['img'], 800, p['name'])}</div><div class="tx"><span class="tag"><i class="{p['icon']}"></i> {dict(cats)[p['cat']]}</span><h3>{p['name']}</h3><p>{p['tagline']}.</p><ul>{li}</ul>
<div class="acts"><a href="{p['slug']}.html" class="btn btn-d">View Details <i class="fa-solid fa-arrow-right"></i></a><a href="#" class="btn btn-l" data-open-enquiry data-product="{p['name']}">Get Quote</a></div></div></div>'''
    body += f'''<section class="sec"><div class="wrap">
 {head('<i class="fa-solid fa-grip"></i> Product Range', 'Browse Our <em>Products</em>', side=flt)}
 <div class="g2" id="plist">{cards}</div>
</div></section>'''
    body += materials_sec()
    body += f'''<section class="sec"><div class="wrap">{head('<i class="fa-solid fa-diagram-project"></i> How We Work', 'From Enquiry to <em>Delivery</em>', '', True)}{steps4()}</div></section>'''
    body += stats('line')
    body += industries_grid(dark=False)
    body += cta('Need a <em>Custom Rubber Part</em>? Send Your Drawing or Sample.', 'We develop moulds and deliver precision rubber components that match your exact requirement.')
    body += testimonials()
    body += faq(GENERAL_FAQS, 'caliper')
    body += enquiry()
    page('products.html', 'Rubber Products | O-Rings, Seals, Gaskets, Bushes – Radical Polymers',
         'Explore Radical Polymers rubber products: O-rings, seals, gaskets, washers, sheets, bushes, profiles, diaphragms, molded and custom rubber parts.', 'products', body)

def product(p):
    others = [x for x in PRODUCTS if x['slug'] != p['slug']]
    side_links = ''.join(f'<a href="{x["slug"]}.html"{" class=on" if x["slug"] == p["slug"] else ""}>{x["name"]}<i class="fa-solid fa-chevron-right"></i></a>' for x in PRODUCTS)
    gal = [p['img']] + p['gal']
    galh = ''.join(f'<div class="img" data-lb>{img(k, 1100 if n == 0 else 700, p["name"])}<span class="zoom"><i class="fa-solid fa-expand"></i></span></div>' for n, k in enumerate(gal[:3]))
    specs = ''.join(f'<tr><td>{a}</td><td>{b}</td></tr>' for a, b in p['specs'] + COMMON_SPECS)
    mats = ''.join(f'<span><i class="fa-solid fa-flask"></i>{m}</span>' for m in p['mats'])
    apps = ''.join(f'<div class="ac rv d{k}">{img(im, 700, t)}<span class="ii"><i class="{ic}"></i></span><h3>{t}</h3><p>{d}</p></div>' for k, (ic, t, d, im) in enumerate(p['apps']))
    why = ''.join(f'<div><i class="{ic}"></i><div><b>{t}</b><span>{d}</span></div></div>' for ic, t, d in WHY8[:6])
    body = phero([('Products', 'products.html'), (p['name'],)], f'<i class="{p["icon"]}"></i> {p["name"]}', f'{p["name"]} <em>Manufacturer</em>', p['tagline'] + ' — made in Ghaziabad, supplied across India.',
                 p['img'], ['Custom Sizes', ', '.join(p['mats'][:3]), 'Bulk & Small Orders'])
    body += f'''<section class="sec"><div class="wrap pd">
<div class="pd-main">
 <div class="blk rv"><div class="blk-h"><span class="eyebrow"><i class="fa-solid fa-circle-info"></i> Overview</span><h2>About Our <em>{p['name']}</em></h2></div>
  <div class="pd-gal">{galh}</div><div class="prose" style="margin-top:30px">{''.join(f'<p>{x}</p>' for x in p['intro'])}</div>
  <div style="display:flex;gap:12px;flex-wrap:wrap"><a href="#" class="btn btn-d" data-open-enquiry data-product="{p['name']}">Request a Quote <i class="fa-solid fa-arrow-right"></i></a><a href="https://wa.me/919711114333" target="_blank" class="btn btn-l"><i class="fa-brands fa-whatsapp" style="color:#25d366"></i> WhatsApp Us</a></div></div>
 <div class="blk"><div class="blk-h rv"><span class="eyebrow"><i class="fa-solid fa-star"></i> Key Features</span><h2>Why Choose Our <em>{p['short']}</em></h2></div>{fcards(p['features'], 3)}</div>
 <div class="blk rv"><div class="blk-h"><span class="eyebrow"><i class="fa-solid fa-table-list"></i> Specifications</span><h2>Technical <em>Details</em></h2><p>Typical specifications — final values are confirmed as per your drawing or application.</p></div>
  <div class="tbl-wrap"><table class="mat-t"><thead><tr><th>Parameter</th><th>Details</th></tr></thead><tbody>{specs}</tbody></table></div></div>
 <div class="blk rv"><div class="blk-h"><span class="eyebrow"><i class="fa-solid fa-flask"></i> Materials</span><h2>Available <em>Compounds</em></h2><p>Selected according to temperature, oil, water and chemical exposure.</p></div><div class="mchips">{mats}</div></div>
 <div class="blk"><div class="blk-h rv"><span class="eyebrow"><i class="fa-solid fa-screwdriver-wrench"></i> Applications</span><h2>Where Our <em>{p['short']}</em> Are Used</h2></div><div class="g2">{apps}</div></div>
 <div class="blk rv"><div class="blk-h"><span class="eyebrow"><i class="fa-solid fa-thumbs-up"></i> Our Advantage</span><h2>Why Buy From <em>Radical Polymers</em></h2></div><div class="chk-g">{why}</div></div>
</div>
<aside class="pd-side">
 <div class="sb-box sb-links"><h4>Our Products</h4>{side_links}</div>
 <div class="sb-cta"><div class="img">{img('operator', 600)}</div><h4>Need {p['short']} in a Custom Size?</h4><p>Share your drawing, sample or dimensions — we'll send a quote within 24 hours.</p><a class="ph" href="tel:+919711114333"><i class="fa-solid fa-phone"></i>+91 9711114333</a><a href="#" class="btn btn-g" data-open-enquiry data-product="{p['name']}">Get a Free Quote</a></div>
 <div class="sb-box"><h4>Quick Contact</h4><ul class="cl" style="color:var(--ink2)"><li style="margin-bottom:14px"><i class="fa-regular fa-envelope" style="width:40px;height:40px;border-radius:10px;background:var(--soft);color:var(--gold);display:grid;place-items:center;flex-shrink:0"></i><div><small style="color:var(--mut)">Email</small><b><a href="mailto:sales@radicalpolymer.com" style="color:var(--ink);font-size:14px">sales@radicalpolymer.com</a></b></div></li><li><i class="fa-solid fa-location-dot" style="width:40px;height:40px;border-radius:10px;background:var(--soft);color:var(--gold);display:grid;place-items:center;flex-shrink:0"></i><div><small style="color:var(--mut)">Address</small><b style="color:var(--ink);font-size:14px">155-A Model Town West, Ghaziabad</b></div></li></ul></div>
</aside>
</div></section>'''
    body += f'''<section class="sec u-soft"><div class="wrap">{head('<i class="fa-solid fa-diagram-project"></i> How We Work', 'From Enquiry to <em>Delivery</em>', '', True)}{steps4()}</div></section>'''
    ind_cards = ''.join(f'<a href="{I[s]["slug"]}.html" class="ac rv d{k}" style="height:300px">{img(I[s]["img"], 700, I[s]["name"])}<span class="ii"><i class="{I[s]["icon"]}"></i></span><h3>{I[s]["name"]}</h3><p>{I[s]["tagline"]}</p></a>' for k, s in enumerate(p['ind']))
    body += f'''<section class="sec"><div class="wrap">{head('<i class="fa-solid fa-city"></i> Industries', 'Industries <em>Served</em>', f"Our {p['short'].lower()} are trusted across these sectors.")}<div class="g3">{ind_cards}</div></div></section>'''
    i = uid('r')
    rel = ''.join(product_card(x) for x in others)
    body += f'''<section class="sec u-soft"><div class="wrap">
 <div class="sec-head rv"><div><span class="eyebrow"><i class="fa-solid fa-boxes-stacked"></i> More Products</span><h2 class="h2" style="margin:0">Related <em>Products</em></h2></div><div class="sl-ctrl" id="{i}"><a href="products.html" class="btn btn-l">All Products</a><button class="ar prev" aria-label="Previous"><i class="fa-solid fa-arrow-left"></i></button><button class="ar next" aria-label="Next"><i class="fa-solid fa-arrow-right"></i></button></div></div>
 <div class="slider rv" data-ctrl="#{i}"><div class="sl-track rel">{rel}</div><div class="sl-dots"></div></div>
</div></section>'''
    body += cta(f'Get a Quote for <em>{p["name"]}</em>', 'Standard or custom — tell us the size, material and quantity you need.')
    body += faq(p['faqs'], 'measure', f'{p["short"]} — <em>FAQs</em>')
    body += enquiry()
    page(p['slug'] + '.html', f'{p["name"]} Manufacturer in Ghaziabad | Radical Polymers',
         f'{p["name"]} manufacturer in Ghaziabad – {p["tagline"].lower()}. Custom sizes in {", ".join(p["mats"][:4])}. Get a quote from Radical Polymers.', 'products', body, product=p['name'])

def industries():
    body = phero([('Industries',)], '<i class="fa-solid fa-city"></i> Industries', 'Rubber Solutions for <em>Every Industry</em>',
                 'From automotive and engineering to process plants, electrical equipment and heavy machinery — our components keep critical equipment sealed and running.',
                 'pipes', ['Automotive', 'Industrial', 'Electrical', 'Machinery'])
    body += split('engineers', f'''<span class="eyebrow"><i class="fa-solid fa-handshake"></i> Industry Expertise</span><h2 class="h2">Parts Built Around <em>Your Application</em></h2>
<p>Every industry places different demands on rubber — oil and fuel in automotive, steam and chemicals in process plants, insulation in electrical equipment, and heavy vibration in machinery.</p>
<p>We start by understanding where and how the part will be used, then select the right compound, hardness and design.</p>
{tk(['Application-specific compounds', 'Drawing-accurate parts', 'OEM & replacement supply', 'Small to bulk quantities'])}
<a href="#" class="btn btn-d" data-open-enquiry>Discuss Your Requirement <i class="fa-solid fa-arrow-right"></i></a>''', badge=('5', 'Core industries served', False), mini='caliper')
    rows = ''
    for k, ind in enumerate(INDUSTRIES):
        prods = ''.join(f'<li><i class="fa-solid fa-circle-check"></i><a href="{s}.html">{P[s]["name"]}</a></li>' for s in ind['products'][:4])
        rows += split(ind['img'], f'''<span class="eyebrow"><i class="{ind['icon']}"></i> 0{k+1} · {ind['name']}</span><h2 class="h2">{ind['name']} <em>Industry</em></h2><p>{ind['intro'][0]}</p>
<ul class="tk c2">{prods}</ul><a href="{ind['slug']}.html" class="btn btn-d">Explore {ind['name']} <i class="fa-solid fa-arrow-right"></i></a>''', rev=(k % 2 == 1), soft=(k % 2 == 0), sm=True)
    body += rows
    body += stats('pipes2')
    body += products_grid(title='Products Used <em>Across Industries</em>', soft=False)
    body += cta('Have an <em>Industry-Specific</em> Requirement?', 'Our team will recommend the right compound and design for your application.')
    body += testimonials()
    body += faq(GENERAL_FAQS, 'valves2')
    body += enquiry()
    page('industries.html', 'Industries We Serve | Automotive, Industrial, Electrical – Radical Polymers',
         'Rubber components for automotive, engineering, industrial, electrical and machinery applications from Radical Polymers, Ghaziabad.', 'industries', body)

def industry(ind):
    body = phero([('Industries', 'industries.html'), (ind['name'],)], f'<i class="{ind["icon"]}"></i> {ind["name"]} Industry', f'Rubber Components for <em>{ind["name"]}</em>',
                 ind['tagline'] + '.', ind['img'], ['Custom Development', 'Right Compound', 'On-Time Supply'])
    body += split(ind['gal'][0], f'''<span class="eyebrow"><i class="{ind['icon']}"></i> Overview</span><h2 class="h2">Serving the <em>{ind['name']}</em> Sector</h2>
{''.join(f'<p>{x}</p>' for x in ind['intro'])}
<a href="#" class="btn btn-d" data-open-enquiry>Send Your Requirement <i class="fa-solid fa-arrow-right"></i></a>''', badge=('350+', 'Happy clients across India', True), mini=ind['gal'][1])
    ch = ''.join(f'<div><i class="fa-solid fa-triangle-exclamation"></i><div><b>{c}</b><span>Handled through the right compound, design and quality checks.</span></div></div>' for c in ind['challenges'])
    body += f'''<section class="sec u-soft"><div class="wrap">{head('<i class="fa-solid fa-lightbulb"></i> Challenges We Solve', f'What {ind["name"]} <em>Applications Demand</em>', 'We design and select materials around these real-world conditions.')}<div class="chk-g rv">{ch}</div></div></section>'''
    body += f'''<section class="sec"><div class="wrap">{head('<i class="fa-solid fa-screwdriver-wrench"></i> Applications', f'Where We Support <em>{ind["name"]}</em>', '', True)}{fcards(ind['uses'], 3)}</div></section>'''
    body += products_grid(ind['products'], f'Products for <em>{ind["name"]}</em>', eyebrow='Recommended Products')
    body += stats(ind['gal'][2])
    body += gallery([ind['img']] + ind['gal'] + ['floor'], [(ind['name'], 'Application'), ('Field Use', ind['name']), ('Components', 'In service'), ('Equipment', ind['name']), ('Production', 'Our facility')],
                    f'{ind["name"]} <em>Gallery</em>')
    body += process_tl(soft=True)
    body += industries_grid(dark=True, title='Other Industries <em>We Serve</em>', exclude=ind['slug'])
    body += testimonials(soft=False)
    body += cta(f'Rubber Parts for <em>{ind["name"]}</em> — Developed to Fit', 'Share your drawing or sample and get a quick quotation.')
    body += faq(GENERAL_FAQS, ind['gal'][1], soft=True)
    body += enquiry()
    page(ind['slug'] + '.html', f'Rubber Parts for {ind["name"]} Industry | Radical Polymers',
         f'Rubber O-rings, seals, gaskets and custom parts for the {ind["name"].lower()} industry. {ind["tagline"]}. Radical Polymers, Ghaziabad.', 'industries', body)

MFG3 = [('manufacturing-facility', 'Manufacturing Facility', 'fa-solid fa-warehouse', 'floor', 'Modern moulding presses and finishing equipment under one roof.'),
        ('quality-testing', 'Quality & Testing', 'fa-solid fa-microscope', 'caliper', 'Dimensional, hardness and visual checks on every lot.'),
        ('custom-manufacturing', 'Custom Manufacturing', 'fa-solid fa-pen-ruler', 'blueprint', 'Parts developed to your drawing or sample.')]

def mfg_cards(exclude=None):
    return '<div class="g3">' + ''.join(f'<a href="{s}.html" class="ac rv d{k}" style="height:380px">{img(im, 800, n)}<span class="ii"><i class="{ic}"></i></span><h3>{n}</h3><p>{d}</p></a>' for k, (s, n, ic, im, d) in enumerate(m for m in MFG3 if m[0] != exclude)) + '</div>'

CAPS = [('fa-solid fa-compress', 'Compression Moulding', 'For O-rings, seals, gaskets and moulded parts.'), ('fa-solid fa-syringe', 'Injection Moulding', 'For repeatable, precise components.'),
        ('fa-solid fa-pen-ruler', 'Mould Development', 'New moulds developed for your part.'), ('fa-solid fa-flask', 'Compound Selection', 'Material matched to the application.'),
        ('fa-solid fa-scissors', 'Trimming & Finishing', 'Clean edges and flash-free finish.'), ('fa-solid fa-microscope', 'Inspection', 'Dimensional, hardness and visual checks.'),
        ('fa-solid fa-boxes-packing', 'Packing', 'Safe packing as per your requirement.'), ('fa-solid fa-truck-fast', 'Dispatch', 'Pan-India delivery on schedule.')]

def manufacturing():
    body = phero([('Manufacturing',)], '<i class="fa-solid fa-industry"></i> Manufacturing', 'Made In-House, <em>Made Right</em>',
                 'From compound selection to moulding, trimming, inspection and packing — every stage happens under one roof at our Ghaziabad facility.',
                 'machine', ['20+ Modern Machines', '80+ Team Members', 'In-House Moulds'])
    body += strip()
    body += split('operator', f'''<span class="eyebrow"><i class="fa-solid fa-industry"></i> Our Capability</span><h2 class="h2">Complete Control from <em>Raw Material to Dispatch</em></h2>
<p>Because we manufacture in-house, we control quality, cost and timelines at every step. That means consistent parts, fair pricing and dependable delivery.</p>
{tk(['Compression & injection moulding', 'In-house mould development', 'Compound selection support', 'Lot-wise inspection', 'Small to bulk production', 'Organised packing & dispatch'])}
<a href="manufacturing-facility.html" class="btn btn-d">View Our Facility <i class="fa-solid fa-arrow-right"></i></a>''', badge=('20+', 'Modern machines', True), mini='caliper')
    body += f'''<section class="sec u-soft"><div class="wrap">{head('<i class="fa-solid fa-layer-group"></i> Manufacturing', 'Explore Our <em>Capabilities</em>', '', True)}{mfg_cards()}</div></section>'''
    body += f'''<section class="sec"><div class="wrap">{head('<i class="fa-solid fa-gears"></i> What We Do', 'In-House <em>Processes</em>', 'Everything needed to take a rubber part from idea to delivery.')}{fcards(CAPS, 4)}</div></section>'''
    body += stats('robot')
    body += process_tl()
    body += gallery(['floor', 'robot', 'caliper', 'assembly', 'warehouse'], [('Production Floor', 'Moulding & finishing'), ('Modern Machines', '20+ equipment'), ('Precision Checks', 'Dimensional inspection'), ('Skilled Team', '80+ members'), ('Packing & Dispatch', 'Pan-India delivery')])
    body += materials_sec()
    body += cta('Have a Part to <em>Develop or Manufacture</em>?', 'Share your drawing or sample — our team will get back with a quote.')
    body += faq(GENERAL_FAQS, 'machine2')
    body += enquiry()
    page('manufacturing.html', 'Rubber Manufacturing Capabilities | Radical Polymers, Ghaziabad',
         'In-house rubber moulding, mould development, inspection and dispatch at Radical Polymers, Ghaziabad. Compression and injection moulded rubber parts.', 'manufacturing', body)

def facility():
    body = phero([('Manufacturing', 'manufacturing.html'), ('Manufacturing Facility',)], '<i class="fa-solid fa-warehouse"></i> Manufacturing Facility', 'Our <em>Manufacturing</em> Facility',
                 'A wide and well-functional infrastructural unit in Ghaziabad, equipped with modern moulding presses and run by a skilled team.',
                 'floor', ['Ghaziabad, Uttar Pradesh', '20+ Machines', '80+ Members'])
    body += split('machine2', f'''<span class="eyebrow"><i class="fa-solid fa-warehouse"></i> Infrastructure</span><h2 class="h2">Built for <em>Consistent Output</em></h2>
<p>Our infrastructure plays an important role in the growth of our company. The facility is organised into dedicated areas for compound preparation, moulding, finishing, inspection and dispatch.</p>
<p>This layout keeps material flow smooth and makes it easier to maintain quality and meet delivery commitments.</p>
{tk(['Compound preparation area', 'Moulding section', 'Trimming & finishing', 'Inspection area', 'Finished goods store', 'Packing & dispatch'])}''', badge=('2013', 'Operating since', False), mini='robot')
    areas = [('fa-solid fa-flask', 'Compound Preparation', 'Raw compound is checked and prepared for the selected material grade.'),
             ('fa-solid fa-compress', 'Moulding', 'Compression and injection moulding presses for a wide range of parts.'),
             ('fa-solid fa-scissors', 'Finishing', 'Parts are trimmed and de-flashed for a clean finish.'),
             ('fa-solid fa-microscope', 'Inspection', 'Lot-wise dimensional, hardness and visual checks.')]
    body += f'''<section class="sec u-soft"><div class="wrap">{head('<i class="fa-solid fa-route"></i> Production Flow', 'How Parts Move Through <em>Our Facility</em>', '', True)}{steps4(areas)}</div></section>'''
    body += f'''<section class="sec"><div class="wrap">{head('<i class="fa-solid fa-gears"></i> Capabilities', 'What Our Facility <em>Can Do</em>')}{fcards(CAPS, 4)}</div></section>'''
    body += stats('line')
    body += gallery(['floor', 'operator', 'robot', 'assembly', 'boxes'], [('Production Floor', 'Moulding & finishing'), ('Moulding Press', 'In operation'), ('Equipment', 'Modern machines'), ('Team at Work', 'Skilled members'), ('Ready for Dispatch', 'Packed goods')], 'Facility <em>Gallery</em>')
    body += split('warehouse', f'''<span class="eyebrow"><i class="fa-solid fa-truck-fast"></i> Packing &amp; Dispatch</span><h2 class="h2">Safe Packing, <em>On-Time Delivery</em></h2>
<p>Finished parts are counted, packed in poly bags and cartons (or as you require) and dispatched across India within the promised time-frame.</p>
{tk(['Lot-wise packing & labelling', 'Custom packing on request', 'Pan-India dispatch', 'Regular schedule supply'])}
<a href="#" class="btn btn-d" data-open-enquiry>Plan Your Order <i class="fa-solid fa-arrow-right"></i></a>''', rev=True, soft=True, badge=('350+', 'Clients served', True))
    body += f'''<section class="sec"><div class="wrap">{head('<i class="fa-solid fa-layer-group"></i> Manufacturing', 'More About <em>How We Work</em>', '', True)}{mfg_cards('manufacturing-facility')}</div></section>'''
    body += cta('Visit or <em>Talk to Our Team</em>', 'Call us to discuss your requirement or plan a visit to our Ghaziabad facility.')
    body += faq(GENERAL_FAQS, 'assembly', soft=True)
    body += enquiry()
    page('manufacturing-facility.html', 'Manufacturing Facility | Radical Polymers, Ghaziabad',
         'Radical Polymers manufacturing facility in Ghaziabad: rubber compound preparation, compression and injection moulding, finishing, inspection and dispatch.', 'manufacturing', body)

def quality():
    body = phero([('Manufacturing', 'manufacturing.html'), ('Quality & Testing',)], '<i class="fa-solid fa-microscope"></i> Quality &amp; Testing', 'Quality That <em>Doesn’t Leak</em>',
                 'Every batch is checked at multiple stages — from raw material to final packing — before it leaves our facility.',
                 'caliper', ['Raw Material Checks', 'Dimensional Inspection', 'Hardness Testing'])
    body += split('measure', f'''<span class="eyebrow"><i class="fa-solid fa-shield-halved"></i> Our Approach</span><h2 class="h2">Quality Built Into <em>Every Step</em></h2>
<p>Quality is not a single check at the end. We control it from compound selection through moulding, finishing and packing — so issues are caught early and parts are consistent from batch to batch.</p>
{tk(['Compound verified before production', 'In-process checks during moulding', 'Dimensions checked against drawing', 'Hardness (Shore A) verified', 'Visual inspection for flash & defects', 'Lot-wise packing & labelling'])}''', badge=('98%', 'Product quality rating', True), mini='lab')
    q = [('fa-solid fa-flask-vial', 'Raw Material Check', 'Compound verified before production begins.', 'lab'),
         ('fa-solid fa-ruler', 'Dimensional Accuracy', 'Sizes checked against drawing tolerances.', 'caliper'),
         ('fa-solid fa-gauge-high', 'Hardness Testing', 'Shore A hardness verified for consistency.', 'measure'),
         ('fa-solid fa-eye', 'Final Visual Inspection', 'Flash, finish and defects checked before packing.', 'clipboard')]
    items = ''
    for k, (ic, t, d, im) in enumerate(q):
        box = f'<div class="box rv"><div class="img">{img(im, 400)}</div><div class="tx"><small>STAGE 0{k+1}</small><h3><i class="{ic}" style="color:var(--gold)"></i>{t}</h3><p>{d}</p></div></div>'
        items += (f'<div class="ts">{box}<div class="dot">0{k+1}</div></div>' if k % 2 == 0 else f'<div class="ts right"><div class="dot">0{k+1}</div>{box}</div>')
    body += f'''<section class="sec u-soft"><div class="wrap">{head('<i class="fa-solid fa-list-check"></i> Inspection Stages', 'Our <em>Quality Process</em>', '', True)}<div class="tl"><div class="fill"></div>{items}</div></div></section>'''
    tests = [('Dimensional check', 'Vernier caliper / gauges', 'ID, OD, cross-section, thickness as per drawing'), ('Hardness', 'Shore A durometer', 'Within agreed hardness range'),
             ('Visual inspection', 'Trained inspectors', 'No flash, cuts, voids or surface defects'), ('Material verification', 'Compound records', 'Correct compound for the order'),
             ('Fit check', 'Sample / mating part', 'Fit verified where samples are provided'), ('Count & packing', 'Lot-wise', 'Correct quantity and labelling')]
    rows = ''.join(f'<tr><td>{a}</td><td>{b}</td><td>{c}</td></tr>' for a, b, c in tests)
    body += f'''<section class="sec"><div class="wrap">{head('<i class="fa-solid fa-table-list"></i> Checks', 'What We <em>Check</em>', 'Typical checks performed on our rubber components.')}
<div class="tbl-wrap rv"><table class="mat-t"><thead><tr><th>Check</th><th>Method</th><th>Acceptance</th></tr></thead><tbody>{rows}</tbody></table></div></div></section>'''
    body += f'''<section class="sec qual pt-0"><div class="wrap">
 <div class="rv"><span class="eyebrow"><i class="fa-solid fa-heart"></i> Results</span><h2 class="h2">Why Clients <em>Stay With Us</em></h2><p class="lead">Consistent quality is the reason most of our business comes from repeat clients.</p>
  <ul class="q-list"><li><div class="qi"><i class="fa-solid fa-rotate"></i></div><div><b>Repeatable Batches</b><span>Same quality order after order.</span></div></li><li><div class="qi"><i class="fa-solid fa-circle-check"></i></div><div><b>Fewer Rejections</b><span>Problems caught before dispatch.</span></div></li><li><div class="qi"><i class="fa-solid fa-handshake"></i></div><div><b>Transparent Communication</b><span>We share issues and solutions openly.</span></div></li></ul></div>
 <div class="q-vis img rv d1">{img('clipboard', 1100)}<div class="q-card"><h3>Client satisfaction</h3>
  <div class="meter"><div><span>Product Quality</span><span>98%</span></div><div class="tr"><i style="--w:98%"></i></div></div>
  <div class="meter"><div><span>On-Time Delivery</span><span>95%</span></div><div class="tr"><i style="--w:95%"></i></div></div>
  <div class="meter"><div><span>Custom Development</span><span>92%</span></div><div class="tr"><i style="--w:92%"></i></div></div></div></div>
</div></section>'''
    body += stats('lab')
    body += f'''<section class="sec"><div class="wrap">{head('<i class="fa-solid fa-layer-group"></i> Manufacturing', 'More About <em>How We Work</em>', '', True)}{mfg_cards('quality-testing')}</div></section>'''
    body += testimonials()
    body += cta('Quality Parts, <em>Every Batch</em>', 'Tell us your requirement and quality expectations — we will meet them.')
    body += faq(GENERAL_FAQS, 'measure')
    body += enquiry()
    page('quality-testing.html', 'Quality & Testing | Radical Polymers Rubber Products',
         'Quality control at Radical Polymers: raw material checks, dimensional inspection, Shore A hardness testing and visual inspection on every lot.', 'manufacturing', body)

def custom():
    body = phero([('Manufacturing', 'manufacturing.html'), ('Custom Manufacturing',)], '<i class="fa-solid fa-pen-ruler"></i> Custom Manufacturing', 'Any Size. Any Shape. <em>Any Compound.</em>',
                 'Send us a drawing or a sample — we develop the mould and deliver precision rubber parts that match exactly.',
                 'blueprint', ['From Drawing', 'From Sample', 'Small to Bulk'])
    body += split('custom', f'''<span class="eyebrow"><i class="fa-solid fa-pen-ruler"></i> Custom Development</span><h2 class="h2">When Standard Parts <em>Won’t Do</em></h2>
<p>Many applications need rubber parts that are not available off the shelf — a non-standard O-ring size, a special gasket shape, or a spare part for older machinery.</p>
<p>Our team develops these parts end-to-end: compound selection, mould development, sampling and production.</p>
{tk(['Develop from 2D/3D drawings', 'Reverse-engineer from samples', 'Compound & hardness selection', 'Sample approval before bulk', 'OEM & replacement parts', 'Flexible quantities'])}
<a href="#" class="btn btn-d" data-open-enquiry data-product="Custom Rubber Parts">Start Your Project <i class="fa-solid fa-arrow-right"></i></a>''', badge=('200+', 'Projects completed', True), mini='cad')
    share = [('fa-solid fa-file-pen', 'Drawing or Sample', 'A dimensioned drawing or a good-condition sample.'), ('fa-solid fa-location-crosshairs', 'Application', 'What the part does and where it is fitted.'),
             ('fa-solid fa-temperature-half', 'Operating Conditions', 'Temperature, media in contact and pressure.'), ('fa-solid fa-gauge', 'Hardness & Colour', 'If known — otherwise we will recommend.'),
             ('fa-solid fa-hashtag', 'Quantity', 'Expected order and annual volume.'), ('fa-solid fa-calendar-check', 'Timeline', 'When you need samples and supply.')]
    body += f'''<section class="sec u-soft"><div class="wrap">{head('<i class="fa-solid fa-clipboard-list"></i> What to Share', 'Information That <em>Speeds Up Development</em>', '', True)}{fcards(share, 3, True)}</div></section>'''
    jr = [('fa-solid fa-comments', 'Requirement Review', 'Step 1', 'We study your drawing/sample and application.'), ('fa-solid fa-flask', 'Compound Selection', 'Step 2', 'Right material and hardness chosen.'),
          ('fa-solid fa-cube', 'Mould & Sample', 'Step 3', 'Mould developed and samples made for approval.'), ('fa-solid fa-truck-fast', 'Bulk Production', 'Step 4', 'Production, inspection and dispatch.')]
    body += f'''<section class="sec"><div class="wrap">{head('<i class="fa-solid fa-route"></i> Our Process', 'From Idea to <em>Approved Part</em>', '', True)}<div class="jr">''' + ''.join(f'<div class="it rv d{k}"><div class="dot"><i class="{ic}"></i></div><small>{y}</small><h3>{t}</h3><p>{d}</p></div>' for k, (ic, t, y, d) in enumerate(jr)) + '</div></div></section>'
    ex = [('fa-regular fa-circle', 'Non-Standard O-Rings', 'Special ID / cross-section sizes', 'oring'), ('fa-regular fa-square', 'Special Gaskets', 'Custom shapes & hole patterns', 'gasket'),
          ('fa-solid fa-screwdriver-wrench', 'Replacement Spares', 'Parts for older machines', 'engine_mech'), ('fa-solid fa-cubes', 'Moulded Components', 'Boots, caps, buffers & more', 'molded')]
    body += f'''<section class="sec ind"><div class="wrap">{head('<i class="fa-solid fa-shapes"></i> Examples', 'Custom Parts <em>We Develop</em>')}<div class="g4">''' + ''.join(f'<div class="ac rv d{k}" style="height:360px">{img(im, 700, t)}<span class="ii"><i class="{ic}"></i></span><h3>{t}</h3><p>{d}</p></div>' for k, (ic, t, d, im) in enumerate(ex)) + '</div></div></section>'
    body += materials_sec(soft=False)
    body += stats('cad')
    body += f'''<section class="sec u-soft"><div class="wrap">{head('<i class="fa-solid fa-layer-group"></i> Manufacturing', 'More About <em>How We Work</em>', '', True)}{mfg_cards('custom-manufacturing')}</div></section>'''
    body += cta('Have a Drawing or Sample? <em>Let’s Develop It.</em>', 'Share it with us on WhatsApp or email and get a quick quotation.', 'drafting')
    body += faq(P['custom-rubber-parts']['faqs'] + GENERAL_FAQS[2:4], 'blueprint')
    body += enquiry()
    page('custom-manufacturing.html', 'Custom Rubber Parts Manufacturing | From Drawing or Sample – Radical Polymers',
         'Custom rubber parts developed from your drawing or sample: compound selection, mould development, sampling and bulk production by Radical Polymers.', 'manufacturing', body, product='Custom Rubber Parts')

def why():
    body = phero([('Why Choose Us',)], '<i class="fa-solid fa-star"></i> Why Choose Us', 'The <em>Radical</em> Advantage',
                 'A genuine manufacturer — not a trader. That means better control over quality, pricing and delivery for every order, big or small.',
                 'techs', ['Direct Manufacturer', 'Custom Sizes', 'On-Time Delivery'])
    body += strip()
    body += split('handshake2', f'''<span class="eyebrow"><i class="fa-solid fa-handshake"></i> Our Promise</span><h2 class="h2">Reliable Parts, <em>Honest Partnership</em></h2>
<p>Clients choose Radical Polymers because we make it easy to get the right rubber part — at a fair price, on time, with a team that responds quickly.</p>
<p>As the manufacturer, we take responsibility for the part from compound selection to dispatch.</p>
{tk(['Factory-direct pricing', 'Develop any size', 'Right compound advice', 'Lot-wise inspection'])}
<a href="#" class="btn btn-d" data-open-enquiry>Get a Quote <i class="fa-solid fa-arrow-right"></i></a>''', badge=('350+', 'Clients trust our parts', True), mini='oring')
    body += f'''<section class="sec u-soft"><div class="wrap">{head('<i class="fa-solid fa-star"></i> 8 Reasons', 'Why Clients <em>Choose Us</em>', '', True)}{fcards(WHY8, 4, True)}</div></section>'''
    cmp = [('Custom size development', 'Any size, from drawing or sample', 'Limited to stock sizes'), ('Pricing', 'Factory-direct, reasonable rates', 'Extra margin added'),
           ('Material choice', 'NBR, EPDM, Silicone, Viton & more', 'Whatever is available'), ('Quality control', 'In-house inspection every lot', 'No process control'),
           ('Delivery commitment', 'Promised time-frame', 'Depends on supplier'), ('Technical support', 'Direct access to the manufacturer', 'Limited product knowledge')]
    rows = ''.join(f'<tr><td>{a}</td><td style="background:#fdf8ec;font-weight:600"><i class="fa-solid fa-circle-check" style="color:#1f9d55"></i> {b}</td><td><i class="fa-solid fa-circle-xmark" style="color:#e5484d"></i> {c}</td></tr>' for a, b, c in cmp)
    body += f'''<section class="sec"><div class="wrap">{head('<i class="fa-solid fa-scale-balanced"></i> Compare', 'Manufacturer vs <em>Trader</em>', 'Buying directly from a manufacturer makes a real difference.')}
<div class="tbl-wrap rv"><table class="mat-t"><thead><tr><th>What You Get</th><th style="background:var(--gold);color:var(--ink)">Radical Polymers</th><th>Typical Trader</th></tr></thead><tbody>{rows}</tbody></table></div></div></section>'''
    body += stats('techs')
    body += process_tl()
    body += industries_grid()
    body += testimonials()
    body += cta('Experience the <em>Radical Difference</em>', 'Send your requirement and see why clients keep coming back.')
    body += faq(GENERAL_FAQS, 'deal')
    body += enquiry()
    page('why-choose-us.html', 'Why Choose Us | Radical Polymers – Genuine Rubber Manufacturer',
         'Why choose Radical Polymers: direct manufacturer pricing, any size developed, right compound, inspected quality and on-time delivery across India.', 'why', body)

def testimonials_page():
    body = phero([('Testimonials',)], '<i class="fa-solid fa-comments"></i> Testimonials', 'What Our <em>Clients Say</em>',
                 'Real feedback from clients who trust Radical Polymers for their rubber components.', 'handshake', ['5.0 Rated', '350+ Happy Clients', 'Repeat Business'])
    body += f'''<section class="sec"><div class="wrap"><div class="rate-band rv"><div class="big">5.0</div><div><h3>Rated by our happy clients</h3><p>Clients value our product quality, ability to develop any size, fair pricing and on-time delivery.</p></div><div class="st">★★★★★</div></div></div></section>'''
    cards = ''.join(f'<div class="tbig rv d{k}"><i class="fa-solid fa-quote-right qm"></i><div class="st">★★★★★</div><p>“{esc(q)}”</p><div class="who"><div class="av">{a}</div><div><b>{n}</b><span>{r}</span></div></div></div>' for k, (a, n, r, q) in enumerate(TESTIMONIALS))
    body += f'''<section class="sec pt-0"><div class="wrap">{head('<i class="fa-solid fa-star"></i> Reviews', 'Client <em>Reviews</em>')}<div class="tgrid">{cards}</div></div></section>'''
    vals = [('fa-solid fa-award', 'Product Quality', '“Quality is as good as the original.”'), ('fa-solid fa-ruler-combined', 'Any Size Developed', '“They can develop any size you ask.”'),
            ('fa-solid fa-indian-rupee-sign', 'Fair Pricing', '“One of the best in terms of pricing.”'), ('fa-solid fa-truck-fast', 'Reliable Delivery', '“Best in sales, service and delivery.”')]
    body += f'''<section class="sec u-soft"><div class="wrap">{head('<i class="fa-solid fa-heart"></i> What Clients Value', 'Why Clients <em>Recommend Us</em>', '', True)}{fcards(vals, 4)}</div></section>'''
    body += stats('assembly')
    body += split('deal', f'''<span class="eyebrow"><i class="fa-solid fa-pen"></i> Share Your Feedback</span><h2 class="h2">Worked With Us? <em>Tell Us How We Did</em></h2>
<p>Your feedback helps us improve and helps other buyers choose with confidence. Share your experience with our team by email or WhatsApp.</p>
<div style="display:flex;gap:12px;flex-wrap:wrap"><a href="mailto:sales@radicalpolymer.com?subject=Feedback" class="btn btn-d"><i class="fa-regular fa-envelope"></i> Email Feedback</a><a href="https://wa.me/919711114333" target="_blank" class="btn btn-l"><i class="fa-brands fa-whatsapp" style="color:#25d366"></i> WhatsApp</a></div>''', rev=True, sm=True)
    body += products_grid(soft=True, title='Products Our <em>Clients Buy</em>')
    body += cta('Join Our <em>Happy Clients</em>', 'Get a quote for your rubber parts today.')
    body += enquiry()
    page('testimonials.html', 'Client Testimonials | Radical Polymers Reviews',
         'Read what clients say about Radical Polymers rubber O-rings, seals, gaskets and custom parts — quality, pricing and delivery.', 'testimonials', body)

def blog():
    f = BLOG[0]
    body = phero([('Blog',)], '<i class="fa-solid fa-newspaper"></i> Blog &amp; Insights', 'Rubber <em>Knowledge Hub</em>',
                 'Guides, tips and material advice to help you choose, measure and maintain rubber components.', 'paper', ['Guides', 'Materials', 'Maintenance Tips'], acts=False)
    body += f'''<section class="sec"><div class="wrap">
<a href="{f['slug']}.html" class="feat-post rv"><div class="img">{img(f['img'], 1100, f['title'])}</div><div class="tx"><span class="cat">Featured · {f['cat']}</span><div class="meta"><span><i class="fa-regular fa-calendar"></i>{f['date']}</span><span><i class="fa-regular fa-clock"></i>{f['mins']} min read</span></div><h2>{f['title']}</h2><p>{f['excerpt']}</p><span class="btn btn-d" style="align-self:flex-start">Read Article <i class="fa-solid fa-arrow-right"></i></span></div></a>'''
    cats = ['all'] + sorted({b['cat'] for b in BLOG})
    flt = '<div class="filters" data-filter="#bgrid">' + ''.join(f'<button{" class=on" if k == 0 else ""} data-f="{c.lower().replace(" ", "-")}">{"All Articles" if c == "all" else c}</button>' for k, c in enumerate(cats)) + '</div>'
    body += f'''{head('<i class="fa-solid fa-book-open"></i> All Articles', 'Latest <em>Articles</em>', side=flt)}<div class="bgrid" id="bgrid">{''.join(blog_card(b) for b in BLOG)}</div></div></section>'''
    body += cta('Have a Technical <em>Question</em>?', 'Our team is happy to help you choose the right rubber part or material.', 'lab')
    body += enquiry()
    page('blog.html', 'Blog | Rubber O-Ring, Seal & Gasket Guides – Radical Polymers',
         'Guides on measuring O-rings, choosing NBR vs EPDM vs Viton, preventing gasket failure and ordering custom rubber parts.', 'blog', body)

def post(b):
    others = [x for x in BLOG if x['slug'] != b['slug']]
    cats = sorted({x['cat'] for x in BLOG})
    body = phero([('Blog', 'blog.html'), (b['cat'],)], f'<i class="fa-solid fa-tag"></i> {b["cat"]}', b['title'], b['excerpt'], b['img'], card=False, acts=False,
                 extra=f'<div class="post-meta"><span><i class="fa-regular fa-user"></i>Radical Polymers Team</span><span><i class="fa-regular fa-calendar"></i>{b["date"]}</span><span><i class="fa-regular fa-clock"></i>{b["mins"]} min read</span></div>')
    rp = ''.join(f'<a href="{x["slug"]}.html"><div class="img">{img(x["img"], 200)}</div><div><b>{x["title"]}</b><small>{x["date"]}</small></div></a>' for x in others[:4])
    cl = ''.join(f'<a href="blog.html">{c}</a>' for c in cats)
    pl = ''.join(f'<a href="{p["slug"]}.html">{p["name"]}<i class="fa-solid fa-chevron-right"></i></a>' for p in PRODUCTS[:6])
    url = f'https://radical-polymer-designs.vercel.app/{b["slug"]}'
    body += f'''<section class="sec"><div class="wrap post">
<article>
 <div class="post-hero-img img rv">{img(b['img'], 1400, b['title'])}</div>
 <div class="article rv">{b['body']}</div>
 <div class="share"><b>Share:</b><a href="https://www.facebook.com/sharer/sharer.php?u={url}" target="_blank" rel="noopener" aria-label="Share on Facebook"><i class="fa-brands fa-facebook-f"></i></a><a href="https://www.linkedin.com/sharing/share-offsite/?url={url}" target="_blank" rel="noopener" aria-label="Share on LinkedIn"><i class="fa-brands fa-linkedin-in"></i></a><a href="https://wa.me/?text={url}" target="_blank" rel="noopener" aria-label="Share on WhatsApp"><i class="fa-brands fa-whatsapp"></i></a><a href="mailto:?subject={esc(b['title'])}&amp;body={url}" aria-label="Share by email"><i class="fa-regular fa-envelope"></i></a></div>
</article>
<aside class="pd-side">
 <div class="sb-box rp"><h4>Recent Articles</h4>{rp}</div>
 <div class="sb-box"><h4>Categories</h4><div class="tags">{cl}</div></div>
 <div class="sb-cta"><div class="img">{img('operator', 600)}</div><h4>Need Help Choosing a Part?</h4><p>Talk to our team — we'll recommend the right size and compound.</p><a class="ph" href="tel:+919711114333"><i class="fa-solid fa-phone"></i>+91 9711114333</a><a href="#" class="btn btn-g" data-open-enquiry>Get a Free Quote</a></div>
 <div class="sb-box sb-links"><h4>Our Products</h4>{pl}<a href="products.html" style="color:var(--gold)">View All Products<i class="fa-solid fa-chevron-right"></i></a></div>
</aside>
</div></section>'''
    body += blog_slider(exclude=b['slug'], title='More <em>Articles</em>').replace('class="sec blog"', 'class="sec blog u-soft"')
    body += cta('Looking for <em>Quality Rubber Parts</em>?', 'Standard sizes or custom development — get a quote today.')
    page(b['slug'] + '.html', f'{b["title"]} | Radical Polymers Blog', b['excerpt'], 'blog', body)

def contact():
    body = phero([('Contact Us',)], '<i class="fa-solid fa-headset"></i> Contact Us', 'Let’s Talk About Your <em>Requirement</em>',
                 'Call, email or send an enquiry — our team usually responds within one working day.', 'deal', ['+91 9711114333', 'sales@radicalpolymer.com', 'Ghaziabad, U.P.'], card=False)
    body += f'''<section class="sec"><div class="wrap"><div class="cinfo">
 <div class="ci-c rv"><i class="fa-solid fa-phone"></i><h3>Call Us</h3><a href="tel:+919711114333">+91 9711114333</a><p>Mon – Sat, 9:30 AM – 7:00 PM</p></div>
 <div class="ci-c rv d1"><i class="fa-regular fa-envelope"></i><h3>Email Us</h3><a href="mailto:sales@radicalpolymer.com">sales@radicalpolymer.com</a><p>Quotes &amp; enquiries</p></div>
 <div class="ci-c rv d2"><i class="fa-solid fa-location-dot"></i><h3>Visit Us</h3><p>155-A Model Town West,<br>Ghaziabad, Uttar Pradesh</p></div>
 <div class="ci-c rv d3"><i class="fa-brands fa-whatsapp"></i><h3>WhatsApp</h3><a href="https://wa.me/919711114333" target="_blank">Chat with us</a><p>Share drawings &amp; photos</p></div>
</div></div></section>'''
    body += enquiry().replace('<section class="enq" id="enquiry">', '<section class="enq" id="enquiry" style="padding-top:0">')
    help_ = [('fa-solid fa-file-invoice', 'Request a Quote', 'Share product, size, material and quantity.'), ('fa-solid fa-pen-ruler', 'Custom Development', 'Send a drawing or sample for a new part.'),
             ('fa-solid fa-flask', 'Material Advice', 'Ask which compound suits your application.'), ('fa-solid fa-truck-fast', 'Order Status', 'Check on an existing order or dispatch.')]
    body += f'''<section class="sec u-soft"><div class="wrap">{head('<i class="fa-solid fa-hand-holding-heart"></i> How We Can Help', 'What You Can <em>Contact Us For</em>', '', True)}{fcards(help_, 4)}</div></section>'''
    body += split('designteam', f'''<span class="eyebrow"><i class="fa-solid fa-lightbulb"></i> Quick Tip</span><h2 class="h2">Get a Faster, <em>More Accurate Quote</em></h2>
<p>Include these details in your enquiry and we can respond faster with the right price and lead time:</p>
{tk(['Product type & size', 'Drawing or photo of sample', 'Material / application', 'Operating temperature', 'Quantity required', 'Delivery location'])}
<a href="https://wa.me/919711114333" target="_blank" class="btn btn-d"><i class="fa-brands fa-whatsapp"></i> Send on WhatsApp</a>''', sm=True, badge=('24h', 'Typical response time', True))
    body += faq(GENERAL_FAQS, 'clipboard', soft=True)
    body += cta('Prefer to <em>Talk Directly</em>?', 'Call our sales team for quick help with your requirement.', 'handshake')
    page('contact-us.html', 'Contact Us | Radical Polymers, Ghaziabad – +91 9711114333',
         'Contact Radical Polymers, 155-A Model Town West, Ghaziabad. Call +91 9711114333 or email sales@radicalpolymer.com for rubber products quotes.', 'contact', body)

POLICIES = {
 'privacy-policy': ('Privacy Policy', 'fa-solid fa-user-shield', [
  ('fa-solid fa-circle-info', 'Introduction', '<p>Radical Polymers (“we”, “us”, “our”) respects your privacy. This policy explains what information we collect through this website, how we use it and the choices you have.</p>'),
  ('fa-solid fa-database', 'Information We Collect', '<p>When you submit an enquiry, quote request or newsletter form, we may collect:</p><ul><li>Your name, phone number and email address</li><li>Company name and city</li><li>Product requirement details you choose to share</li></ul><p>We may also collect basic, non-identifying usage data such as pages visited and browser type.</p>'),
  ('fa-solid fa-gears', 'How We Use Your Information', '<ul><li>To respond to your enquiries and send quotations</li><li>To process and deliver orders</li><li>To share product updates if you have subscribed</li><li>To improve our website and services</li></ul>'),
  ('fa-solid fa-share-nodes', 'Sharing of Information', '<p>We do not sell or rent your personal information. We may share it only with service providers who help us operate our business (for example, courier partners), or where required by law.</p>'),
  ('fa-solid fa-lock', 'Data Security', '<p>We take reasonable measures to protect your information. However, no method of transmission over the internet is completely secure.</p>'),
  ('fa-solid fa-user-check', 'Your Choices', '<p>You may ask us to update or delete your information, or unsubscribe from updates at any time, by emailing <a href="mailto:sales@radicalpolymer.com" style="color:var(--gold)">sales@radicalpolymer.com</a>.</p>'),
  ('fa-solid fa-envelope', 'Contact', '<p>For any privacy questions, contact us at 155-A Model Town West, Ghaziabad, Uttar Pradesh, or call +91 9711114333.</p>')]),
 'cookies-policy': ('Cookies Policy', 'fa-solid fa-cookie-bite', [
  ('fa-solid fa-circle-info', 'What Are Cookies?', '<p>Cookies are small text files stored on your device when you visit a website. They help the site work properly and remember your preferences.</p>'),
  ('fa-solid fa-list', 'How We Use Cookies', '<ul><li><b>Essential:</b> required for basic site functions.</li><li><b>Preference:</b> remember choices such as whether you have already seen our enquiry popup.</li><li><b>Analytics:</b> if enabled, help us understand how visitors use the site.</li></ul>'),
  ('fa-solid fa-globe', 'Third-Party Services', '<p>Our pages load fonts, icons, images and maps from third-party providers (such as Google Fonts, Google Maps, Unsplash and cdnjs). These providers may set their own cookies under their own policies.</p>'),
  ('fa-solid fa-sliders', 'Managing Cookies', '<p>You can block or delete cookies through your browser settings. Some parts of the website may not work as intended if cookies are disabled.</p>'),
  ('fa-solid fa-envelope', 'Contact', '<p>Questions about this policy? Email <a href="mailto:sales@radicalpolymer.com" style="color:var(--gold)">sales@radicalpolymer.com</a>.</p>')]),
 'disclaimer': ('Disclaimer', 'fa-solid fa-scale-balanced', [
  ('fa-solid fa-circle-info', 'General Information', '<p>The information on this website is provided by Radical Polymers for general information purposes only. While we try to keep it accurate and up to date, we make no warranties about its completeness or suitability for any particular purpose.</p>'),
  ('fa-solid fa-table-list', 'Technical Data', '<p>Specifications, temperature ranges and material properties shown are typical values for guidance. Actual performance depends on the compound, design and operating conditions. Please confirm requirements with our team before ordering.</p>'),
  ('fa-solid fa-image', 'Images', '<p>Some images on this website are representative stock photographs and may not show our actual products or facility.</p>'),
  ('fa-solid fa-link', 'External Links', '<p>Links to other websites are provided for convenience. We are not responsible for the content of external sites.</p>'),
  ('fa-solid fa-triangle-exclamation', 'Limitation of Liability', '<p>Radical Polymers will not be liable for any loss or damage arising from the use of information on this website.</p>'),
  ('fa-solid fa-envelope', 'Contact', '<p>For questions, call +91 9711114333 or email <a href="mailto:sales@radicalpolymer.com" style="color:var(--gold)">sales@radicalpolymer.com</a>.</p>')]),
}

def policy(slug):
    t, ic, secs = POLICIES[slug]
    body = phero([(t,)], f'<i class="{ic}"></i> Legal', t, f'Please read this {t.lower()} carefully. It applies to your use of the Radical Polymers website.', 'paper', card=False, acts=False)
    content = ''.join(f'<h2><i class="{i}"></i>{h}</h2>{c}' for i, h, c in secs)
    body += f'<section class="sec"><div class="wrap"><div class="policy rv"><span class="upd"><i class="fa-regular fa-calendar"></i> Last updated: October 2026</span>{content}</div></div></section>'
    body += cta('Have a <em>Question</em>?', 'Our team is happy to help — call or send us an enquiry.')
    page(slug + '.html', f'{t} | Radical Polymers', f'{t} of Radical Polymers website.', None, body)

def notfound():
    body = '''<section class="nf"><div class="wrap"><b>404</b><h1>Page Not Found</h1><p>The page you are looking for doesn’t exist or has been moved.</p>
<div style="display:flex;gap:12px;justify-content:center;flex-wrap:wrap"><a href="index.html" class="btn btn-d"><i class="fa-solid fa-house"></i> Back to Home</a><a href="products.html" class="btn btn-l">View Products</a><a href="contact-us.html" class="btn btn-l">Contact Us</a></div></div></section>'''
    body += products_grid(soft=True, title='Popular <em>Products</em>')
    page('404.html', 'Page Not Found | Radical Polymers', 'Page not found.', None, body)

if __name__ == '__main__':
    build_assets()
    about(); products()
    for p in PRODUCTS: product(p)
    industries()
    for i in INDUSTRIES: industry(i)
    manufacturing(); facility(); quality(); custom()
    why(); testimonials_page(); blog()
    for b in BLOG: post(b)
    contact()
    for s in POLICIES: policy(s)
    notfound()
    print(f'Built {len(PAGES)} pages:', ', '.join(PAGES))
